version: '3.4'

services:
  estateone:
    image: estateone
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3400:3400
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
